# name: Deploy Docs
# on:
#   push:
#     branches:
#       - main
#
# jobs:
#   publish-docs:
#     runs-on: ubuntu-24.04
#     steps:
#       - uses: actions/checkout@v4
#
#       - name: Setup .NET
#         uses: actions/setup-dotnet@v3
#         with:
#           dotnet-version: '8.x'
#
#       - name: Install DocFX
#         run: dotnet tool update -g docfx
#
#       - name: Build Site
#         run: docfx docs/docfx.json
#
#       - name: Deploy to GitHub Pages
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./docs/_site # Where DocFX outputs the HTML
