name: CI
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write
  pages: write

jobs:
  check-template:
    name: Check for .template file
    runs-on: ubuntu-24.04
    outputs:
      is_template: ${{ steps.check.outputs.is_template }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check existence of .template
        id: check
        run: |
          if [ -f ".template" ]; then
            echo "Template file found. Skipping builds."
            echo "is_template=true" >> $GITHUB_OUTPUT
          else
            echo "is_template=false" >> $GITHUB_OUTPUT
          fi
  build:
    name: Build for ${{ matrix.targetPlatform }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: check-template
    if: needs.check-template.outputs.is_template == 'false'
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            targetPlatform: StandaloneLinux64
          - os: windows-2025
            targetPlatform: StandaloneWindows64
          - os: macOS-15
            targetPlatform: StandaloneOSX
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}-

      - name: Build Unity Project
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          projectPath: ./Sandbox.__NAMESPACE__
          allowDirtyBuild: true
  test:
    name: Tests
    needs: check-template
    if: needs.check-template.outputs.is_template == 'false'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: ./Sandbox.__NAMESPACE__/Library
          key: Library-test-${{ hashFiles('**/ProjectSettings/**') }}

      - name: Run Unity Tests
        uses: game-ci/unity-test-runner@v4
        id: tests
        with:
          projectPath: ./Sandbox.__NAMESPACE__
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          customParameters: -debugCodeOptimization -enableCodeCoverage -coverageResultsPath ./coverage-results

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test-Results
          path: artifacts
  sonar-analysis:
    name: SonarQube Analysis
    needs: test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download Test Results
        uses: actions/download-artifact@v4
        with:
          name: Test-Results
          path: artifacts
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
  release:
    name: Release
    runs-on: ubuntu-24.04
    needs: [check-template, build, test, sonar-analysis]
    if: |
      always() &&
      (
        (needs.test.result == 'success' && needs.sonar-analysis.result == 'success' && needs.build.result == 'success') || 
        (needs.check-template.outputs.is_template == 'true')
      ) &&
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

  documentation:
    name: Documentation
    needs: [check-template, release]
    if: |
      always() &&
      (needs.release.result == 'success' || needs.check-template.outputs.is_template == 'true')
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install DocFX
        run: dotnet tool restore

      - name: Build Documentation
        run: bash ./Tools/build-doc.sh

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
